apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: feedback-cj
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: feedback-cj
            image: tbsacr.azurecr.io/feedback-cj:1.0.0
            imagePullPolicy: Always
            resources: 
              limits:
                cpu: 1000m
                memory: 512Mi
              requests:
                cpu: 250m
                memory: 256Mi
            args:
            - java
            - -jar 
            - app.jar
          restartPolicy: OnFailure