apiVersion: batch/v1
kind: CronJob
metadata:
  name: feedback-cj
spec:
  schedule: "*/10 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: feedback-cj
              image: tbsacr.azurecr.io/feedback-cj:1.0.0
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "1"
                  memory: 2Gi # Increased from 1Gi to 2Gi
                requests:
                  cpu: "0.5"
                  memory: 1Gi # Increased from 512Mi to 1Gi
              args:
                - java
                - -jar
                - app.jar
          restartPolicy: OnFailure
