apiVersion: batch/v1
kind: CronJob
metadata:
  name: feedback-cj
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: feedback-cj
            image: tbsacr.azurecr.io/feedback-cj:1.0.0
            imagePullPolicy: Always
            resources: 
              limits:
                cpu: "1"
                memory: 1Gi
              requests:
                cpu: "0.5"
                memory: 512Mi
            args:
            - java
            - -jar 
            - app.jar
          restartPolicy: OnFailure
