name: Deploy to AKS Cluster
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Decrypt large secret
      run: ./scripts/decrypt.sh
      env:
        APPLICATION_PROPERTIES_PASSPHRASE: ${{ secrets.APPLICATION_PROPERTIES_PASSPHRASE }}
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Include local jar
      run: mvn install:install-file -Dfile="lib/PageSuccess-0.0.1-SNAPSHOT.jar" -DgroupId="ca.gc.tbs" -DartifactId="PageSuccess" -Dversion="0.0.1-SNAPSHOT" -Dpackaging=jar -DgeneratePom=true
    
    - name: Build with Maven
      run: mvn install --file pom.xml

    - uses: Azure/docker-login@v1
      with:
        login-server: tbsacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - run: |
        docker build -f ./docker/Dockerfile . -t tbsacr.azurecr.io/feedback-cj:${{ github.sha }}
        docker push tbsacr.azurecr.io/feedback-cj:${{ github.sha }}
        docker build -f ./csv-archive/Dockerfile . -t tbsacr.azurecr.io/feedback-cj/archive-script:${{ github.sha }}
        docker push tbsacr.azurecr.io/feedback-cj/archive-script:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: tbs-prod-aks
        resource-group: tbs-prod-rg
        
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/feedback-cronjob.yml
        images: |
          tbsacr.azurecr.io/feedback-cj:${{ github.sha }}
        namespace: |
          pagesuccess

